name: Generate Preview2

on:
  pull_request:
    types: [assigned, synchronize, reopened, edited]

  
  
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
    
        
    - uses: actions/checkout@v1
      # Find the PR associated with this push, if there is one.
      # This will echo "Your PR is 7", or be skipped if there is no current PR.
    - run: echo "Your PR is ${PR_NUMBER}"
      env:
       PR_NUMBER: ${{ github.event.pull_request.number }}
    
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Sleep for 40 seconds
      uses: jakejarvis/wait-action@master
      with:
        time: '40s'

    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '16.6.1'
    
    - name: Install NPM packages
      run: npm ci
    
    - name: Build project
      run: CI=false npm run build

    - name: Upload production-ready build files
      uses: actions/upload-artifact@v2
      with:
        name: production-files
        path: ./build
  
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: production-files
        path: ./build
        
    - name: Deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.BOT }}
        publish_dir: ./build
        cname: ${{ github.event.pull_request.number }}.pr.blueedge.me
        external_repository: win11bot/pr-${{ github.event.pull_request.number }}
    
    - name: Sleep for 120 seconds
      uses: jakejarvis/wait-action@master
      with:
        time: '120s'
        
    - name: Comment PR
      uses: thollander/actions-comment-pull-request@master
      with:
         message: 'Deploy Preview has been updated !'
         GITHUB_TOKEN: ${{ secrets.BOT }}
